### PR TITLE
Adding fix for complexer alerts, than just strings

### PR DESCRIPTION
**Pull request by matzew**

### CODE REVIEW

**Comment by sebastienblanc** [comment]
:eyes:

**Comment by sebastienblanc** [comment]
:+1:

**Comment by lholmquist** [comment]
testing

**Comment by cvasilak** [comment]
@matzew opened [PR#1](https://github.com/matzew/aerogear-push-helloworld/pull/1/files) with a small polish.

**Comment by lholmquist** [comment]
used the node.js sender and getting notifications from both the iOS app and the test safari app i have running

:+1:  once https://github.com/matzew/aerogear-push-helloworld/pull/1/files makes it in

**Comment by matzew** [comment]
@sebastienblanc @lholmquist @cvasilak cool! merged the other PR

**Comment by abstractj** [comment]
@matzew could you please rebase?

**Comment by matzew** [comment]
@abstractj @cvasilak rebased against the target swift branch

**Comment by cvasilak** [comment]
@matzew thank you :rocket: landed on https://github.com/aerogear/aerogear-push-helloworld/commit/feec5b5e404372234aa470a5aef3a688076a0b07

**Pull request merged**
