### PR TITLE
added podfile support for ios-client (swift)

### PR DESCRIPTION
**Pull request by cvasilak**
Note: Once the https://github.com/aerogear/aerogear-ios-push/issues/41  podspec is merged on 'master' will update this PR to remove reference to the private 'cvasilak' repo in the Podfile

@corinnekrych @matzew mind to review?

### CODE REVIEW

**Comment by matzew** [comment]
trying to run the app, I am getting:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

**Comment by matzew** [comment]
That's on the Pods-AeroGearPushSwift lib

**Comment by corinnekrych** [comment]
+1 on my side
Before merging let's have get the naming right for
https://github.com/aerogear/aerogear-ios-push/pull/41

**Comment by matzew** [comment]
the ObjC version uses a binary dependency. I'd say, let's stay consistent on the Swift bits too, and not introduce CocoaPods here as another dependency

**Comment by cvasilak** [comment]
@matzew @corinnekrych closing this, #agree on the binary dependency (as we have in objective-c port) 

will open a separate: new PR with:
a) removing of the push-sdk code that currently exists
b) addition of the ```Swift``` library framework ```AeroGearPush.framework``` and usage of it (instead of the Pod approach)

**Pull request closed without merging**
