### PR TITLE
replace push-sdk source code with a framework binary artifact

### PR DESCRIPTION
**Pull request by cvasilak**
@corinnekrych @matzew mind to give it a try?

NOTE: This PR should be merged on the 'swift' branch

### CODE REVIEW

**Comment by corinnekrych** [comment]
:eyes:

**Comment by matzew** [comment]
:eyeglasses: at it

**Comment by matzew** [comment]
getting

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/mobile/Containers/Bundle/Application/727EAF16-26B8-47DA-91A7-19043EC6FF63/HelloWorldSwift.app/HelloWorldSwift
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/727EAF16-26B8-47DA-91A7-19043EC6FF63/HelloWorldSwift.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/mobile/Containers/Bundle/Application/727EAF16-26B8-47DA-91A7-19043EC6FF63/HelloWorldSwift.app/Frameworks/libswiftCore.dylib'

	/private/var/mobile/Containers/Bundle/Application/727EAF16-26B8-47DA-91A7-19043EC6FF63/HelloWorldSwift.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/mobile/Containers/Bundle/Application/727EAF16-26B8-47DA-91A7-19043EC6FF63/HelloWorldSwift.app/Frameworks/libswiftCore.dylib'

	/private/var/mobile/Containers/Bundle/Application/727EAF16-26B8-47DA-91A7-19043EC6FF63/HelloWorldSwift.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/mobile/Containers/Bundle/Application/727EAF16-26B8-47DA-91A7-19043EC6FF63/HelloWorldSwift.app/Frameworks/libswiftCore.dylib'

```

**Comment by matzew** [comment]
the AeroGear logo (splash screen) looks a bit odd. Actually the AeroGear logo is completely broken :-)

**Comment by matzew** [comment]
NEVERMIND! I had the wrong developer for signing.


works fine

**Comment by matzew** [comment]
:+1:

**Comment by corinnekrych** [comment]
Register + send a push notification via admin console => works fine
But I have issue with the UI never which is never refreshed with a never end spinning registering... loop
this is due to local notification not being fired.
but not sure what cause the issue though

**Comment by corinnekrych** [comment]
Ah my mistake. I did a copy/paste from UPS console therefore, losing registration to "registered" local event. all good. 
Merging...

**Pull request merged**
